Repository UCLA-Creative-Labs/aurgy-backend, pull requests merged in 2021-12, with the labels that each got.

#1 feat: create DbClient to manage database interacitons
  lib/db-client.ts
  lib/index.ts
  package.json
  utils/logging.ts
  www/index.ts
  yarn.lock
Labels: feature

#5 feat: POST login endpoint to add user data to DB
  jest.config.js
  lib/db-client.ts
  lib/private/CONSTANTS.ts
  lib/private/SPOTIFY_ENDPOINTS.ts
  lib/spotify/access-token.ts
  lib/spotify/index.ts
  lib/spotify/me.ts
  lib/spotify/types.ts
  package.json
  test/utils/form.test.ts
  tsconfig.json
  utils/errors.ts
  utils/form.ts
  utils/index.ts
  www/index.ts
  www/login.ts
  yarn.lock
Labels: feature, pr/do-not-merge

#6 chore: convert linter action to run linter/test/build
  .github/workflows/build.yml
Labels: chore

#9 feat: database item base class and unit tests
  .jest/mocks/oracledb.ts
  .jest/setup/envVars.js
  jest.config.js
  lib/db-client.ts
  lib/db-item.ts
  lib/index.ts
  test/lib/db-client.test.ts
Labels: chore, feature

#12 chore: general documentation on components of the backend
  .mergify.yml
  CONTRIBUTING.md
  docs/README.md
  docs/core.md
  docs/routing.md
  docs/testing.md
  docs/utility.md
Labels: chore

#13 feat: create function to get users' top songs
  lib/spotify/song-update.ts
  lib/spotify/song.ts
  lib/spotify/types.ts
Labels: feature

#15 feat: user class
  .eslintrc.js
  lib/db-client.ts
  lib/db-item.ts
  lib/private/enums.ts
  lib/spotify/types.ts
  lib/user.ts
  www/index.ts
  www/login.ts
  www/me.ts
Labels: feature

#17 fix: update refresh token as part of the POST /me
  lib/user.ts
  www/me.ts
Labels: feature

#18 chore: refactor top songs implementation to reflect design guidelines
  lib/private/SPOTIFY_ENDPOINTS.ts
  lib/song.ts
  lib/spotify/song-update.ts
  lib/spotify/top-songs.ts
  lib/spotify/types.ts
Labels: chore

#19 feat: update top songs for user every time they log in
  lib/db-client.ts
  lib/db-item.ts
  lib/spotify/access-token.ts
  lib/spotify/top-songs.ts
  lib/spotify/types.ts
  lib/user.ts
  www/me.ts
Labels: feature

#20 feat: incorporate jwt for authentication
  package.json
  utils/jwt.ts
  www/me.ts
  yarn.lock
Labels: feature

#22 feat: song database item class and audio features implementation
  lib/index.ts
  lib/private/SPOTIFY_ENDPOINTS.ts
  lib/song.ts
  lib/spotify/audio-features.ts
  lib/spotify/index.ts
  lib/spotify/top-songs.ts
  lib/spotify/types.ts
  lib/user.ts
  www/me.ts
Labels: feature
